### ISSUE TITLE
Will Recycling happen if you put recyclerview under scrollview?

### ISSUE THREAD

**Issue by raghunandankavi2010** [monsterbrain/RecyclerviewTableViewAndroid#3]
Will Recycling happen if you put recyclerview under scrollview.

**Comment by monsterbrain** [comment]
I think yes. You can check via putting a log inside onBind and onCreate to see for yourself I guess. I'll to check later ..

**Comment by raghunandankavi2010** [comment]
No it won't scroll view will keep all its child views in memory. If list is large it will end up in OOM. Then again your table is not large enough to cause this problem. Generally bad idea to put RV in scrollview. performacne implications can be tested further

**Comment by raghunandankavi2010** [comment]
Just to add https://www.youtube.com/watch?v=1ANt65eoNhQ&list=PLOU2XLYxmsILw2VmhxUWyd_imCrJef_iz&index=88 at 15:35

**Comment by monsterbrain** [comment]
Thanks for the info. But I rechecked and put a log inside onCreate, and with 27 items .. 

there were only 15 "oncreate View Holder:" log in logcat ... 

So I don't think 27 items were created and recycle is happening, since onBindView is called on scrolling ..

**Comment by raghunandankavi2010** [comment]
Makes sense!
