### ISSUE TITLE
its not working for large data

### ISSUE THREAD

**Issue by adarshdhakad** [monsterbrain/RecyclerviewTableViewAndroid#4]

**Comment by monsterbrain** [comment]
How large is the data ? Do you have any sample data ?

**Comment by adarshdhakad** [comment]
https://user-images.githubusercontent.com/114132809/209795284-f75df025-f7a9-421a-9c13-fae9d575ee07.mp4

watch this video after getting new data its always in bottom

**Comment by adarshdhakad** [comment]
I mean recycler position issue is there its always in bottom

**Comment by monsterbrain** [comment]
You mean, when you dynamically add the data to the recyclerview ?

**Comment by adarshdhakad** [comment]
yes I am using pagination sometimes it works fine but  with this data its not working

**Comment by adarshdhakad** [comment]
hello thanks for your quick reply I found a solution to my problem 

I was using AsyncDiffer list  that's why 
now i am using ArrayList its working fine 
thanks again
